server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
